language: python

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
    - os: osx
      language: generic
      env: PYTHON_VER=3.7


    - os: linux
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.6
    - os: linux
      language: generic
      env: PYTHON_VER=3.7


before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source tutorial/day4/geometry_analysis/devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - python tutorial/day4/geometry_analysis/devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER tutorial/day4/geometry_analysis/devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test
    # Build and install package
  - python setup.py develop --no-deps


script:
  - cd tutorial/day4/geometry_analysis
  - pytest -v --cov=geometry_analysis source/tests/

notifications:
    email: false

after_success:
  - codecov
